# shellcheck shell=bash
# Distribute instruction files to the agent runtimes installed on this host.
# Sourced by install.sh.
#
# Two delivery paths, both sourced from the same instructions/*.instructions.md
# files in this repo (single source of truth):
#
# 1. VS Code Copilot:
#    Each *.instructions.md is symlinked into every present VS Code prompts
#    directory (desktop + Remote-SSH, Stable + Insiders). Copilot honors
#    YAML frontmatter (`applyTo` globs) so files installed this way only
#    activate when matching the open workspace.
#
# 2. opencode (https://opencode.ai):
#    opencode loads ~/.config/opencode/AGENTS.md as global rules. We
#    generate that file by concatenating instructions/*.instructions.md
#    (frontmatter stripped — opencode rules are global, no `applyTo`).
#    Marked with a sentinel header so re-runs only overwrite our own file
#    and never clobber a hand-maintained one. Skills installed elsewhere
#    (e.g. ~/.agents/skills/ from `td skill install universal`) are
#    symlinked into ~/.config/opencode/skills/ so opencode discovers them.

instructions_src="$DEV_SETUP_ROOT/instructions"

if [[ ! -d "$instructions_src" ]]; then
  log_warn "no instructions directory at $instructions_src; skipping"
  return 0
fi

# ---------------------------------------------------------------------------
# 1. VS Code Copilot symlinks
# ---------------------------------------------------------------------------
# Candidate prompts directories. We install into every one that exists *or*
# whose parent (User/) exists — which catches both desktop and Remote-SSH
# server.
candidate_dirs=(
  "$HOME/.config/Code/User/prompts"
  "$HOME/.vscode-server/data/User/prompts"
  "$HOME/.config/Code - Insiders/User/prompts"
  "$HOME/.vscode-server-insiders/data/User/prompts"
)

linked_any=0
for dir in "${candidate_dirs[@]}"; do
  parent="$(dirname "$dir")"
  if [[ ! -d "$parent" ]]; then
    continue
  fi
  mkdir -p "$dir"
  for src in "$instructions_src"/*.instructions.md; do
    [[ -e "$src" ]] || continue
    name="$(basename "$src")"
    target="$dir/$name"
    if [[ -L "$target" && "$(readlink "$target")" == "$src" ]]; then
      log_info "up to date: $target"
    elif [[ -e "$target" && ! -L "$target" ]]; then
      log_warn "skipping $target (exists and is not a symlink; remove it manually to let dev-setup manage it)"
    else
      ln -sfn "$src" "$target"
      log_info "linked $target -> $src"
      linked_any=1
    fi
  done
done

if [[ $linked_any -eq 0 ]]; then
  log_info "no new VS Code instruction symlinks created"
fi

# ---------------------------------------------------------------------------
# 2. opencode global AGENTS.md (generated)
# ---------------------------------------------------------------------------
# Sentinel marks files we own. If the user wrote their own AGENTS.md we
# leave it alone and warn — they can rename it and reference it from the
# generated one if they want both.
opencode_dir="$HOME/.config/opencode"
agents_md="$opencode_dir/AGENTS.md"
managed_marker='<!-- managed by dev-setup -->'

mkdir -p "$opencode_dir"

if [[ -f "$agents_md" ]] && ! grep -qF "$managed_marker" "$agents_md"; then
  log_warn "opencode: $agents_md exists and is not managed by dev-setup; skipping"
  log_warn "  to let dev-setup manage it, move your content elsewhere and re-run"
else
  log_info "opencode: regenerating $agents_md from $instructions_src/*.instructions.md"
  # Stream into a temp file then rename for atomicity.
  tmp_agents="$(mktemp "$opencode_dir/.AGENTS.md-XXXXXX")"
  {
    printf '%s\n' "$managed_marker"
    printf '<!-- regenerated by dev-setup install-instructions.sh on each install. -->\n'
    printf '<!-- to edit, change files in dev-setup/instructions/ and re-run install.sh. -->\n'
    printf '<!-- frontmatter is stripped because opencode rules are global (no applyTo). -->\n\n'
    for src in "$instructions_src"/*.instructions.md; do
      [[ -e "$src" ]] || continue
      printf '<!-- source: %s -->\n' "$(basename "$src")"
      # Strip YAML frontmatter (between the first two `---` lines), if present.
      awk '
        BEGIN { in_fm = 0 }
        NR == 1 && $0 == "---" { in_fm = 1; next }
        in_fm && $0 == "---" { in_fm = 0; next }
        in_fm { next }
        { print }
      ' "$src"
      printf '\n'
    done
  } > "$tmp_agents"
  mv -f "$tmp_agents" "$agents_md"
  log_info "opencode: wrote $agents_md"
fi

# ---------------------------------------------------------------------------
# 3. opencode skills (symlink ~/.agents/skills/* into ~/.config/opencode/skills/)
# ---------------------------------------------------------------------------
# Skills like the Doist universal skill (~/.agents/skills/todoist-cli/SKILL.md)
# are installed by the CLI that owns them. opencode looks for skills in
# ~/.config/opencode/skills/<name>/SKILL.md, so symlink each subdirectory in.
# Per-subdirectory symlinks (not a single dir-level symlink) so the user can
# still drop opencode-only skills into ~/.config/opencode/skills/ alongside.
agents_skills_src="$HOME/.agents/skills"
opencode_skills="$opencode_dir/skills"
if [[ -d "$agents_skills_src" ]]; then
  mkdir -p "$opencode_skills"
  for skill_src in "$agents_skills_src"/*/; do
    [[ -d "$skill_src" ]] || continue
    skill_src="${skill_src%/}"   # strip trailing slash
    skill_name="$(basename "$skill_src")"
    skill_target="$opencode_skills/$skill_name"
    if [[ -L "$skill_target" && "$(readlink "$skill_target")" == "$skill_src" ]]; then
      log_info "opencode skill up to date: $skill_target"
    elif [[ -e "$skill_target" && ! -L "$skill_target" ]]; then
      log_warn "opencode: skipping $skill_target (exists and is not a symlink)"
    else
      ln -sfn "$skill_src" "$skill_target"
      log_info "opencode: linked skill $skill_target -> $skill_src"
    fi
  done
fi
